Marketing.GestaoVerbas/Controllers/FuncionarioController.cs
using Marketing.GestaoVerbas.Api;
using Marketing.GestaoVerbas.Core;
using Marketing.GestaoVerbas.Core.Grid;
using Marketing.GestaoVerbas.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketing.GestaoVerbas.Controllers
{
    public class FuncionarioController : Controller
    {
        [HttpPost]
        public ActionResult Pesquisar(GridSetings<ViewModel.FuncionarioViewModel> gridSetings)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (gridSetings.Filtro == null)
            {
                gridSetings.Filtro = new ViewModel.FuncionarioViewModel();
                gridSetings.Result = new List<ViewModel.FuncionarioViewModel>();
            }
            else if (gridSetings.Filtro.CodFuncionario != null || !string.IsNullOrEmpty(gridSetings.Filtro.NomFuncionario))
            {
                RetornoApi retornoFuncionarios = FuncionarioApi.List(gridSetings);
                if (retornoFuncionarios.Sucesso)
                {
                    gridSetings = (GridSetings<FuncionarioViewModel>)retornoFuncionarios.Resultado;
                }
                else
                {
                    gridSetings.Result = new List<FuncionarioViewModel>();
                    Util.PreencheTempDataAlerta(this, retornoFuncionarios);
                }
                if (gridSetings.Result.Count == 0)
                    Util.PreencheTempDataAlerta(this, Core.Message.Constantes.NENHUM_REGISTRO_ENCONTRADO, "Atenção", "info");
            }
            else
            {
                Util.PreencheTempDataAlerta(this, Core.Message.Constantes.INFORME_FILTRO, "Atenção", "info");

                gridSetings.Filtro = new ViewModel.FuncionarioViewModel();
                gridSetings.Result = new List<ViewModel.FuncionarioViewModel>();
            }
            
            return PartialView("~/Views/Funcionario/findFuncionario.cshtml", gridSetings);
        }


        [HttpGet]
        public string Select(int codigo)
        {
            if (!Util.ValidaSessao())
            {
                return "";
            }

            GridSetings<ViewModel.FuncionarioViewModel> gridSetings = new GridSetings<FuncionarioViewModel>();
            gridSetings.Filtro = new FuncionarioViewModel();

            gridSetings.Filtro.CodFuncionario = codigo;
            gridSetings.Setings = new Setings();

            gridSetings.Setings.Column = "NomFuncionario";
            gridSetings.Setings.Way = "asc";
            gridSetings.Setings.PageSize = 10;
            gridSetings.Setings.CurrentPage = 1;


            RetornoApi retornoApi = FuncionarioApi.List(gridSetings);
            if (retornoApi.Sucesso)
            {
                gridSetings = (GridSetings<FuncionarioViewModel>)retornoApi.Resultado;
            }
            else
            {
                gridSetings.Result = new List<FuncionarioViewModel>();
                Util.PreencheTempDataAlerta(this, retornoApi);
            }


            if (gridSetings.Result.Count == 0)
                return "Funcionario não encontrado!";
            else
                return gridSetings.Result.First().NomFuncionario;
        }
    }
}

Marketing.GestaoVerbas/Views/Funcionario/findFuncionario.cshtml
@model Marketing.GestaoVerbas.Core.Grid.GridSetings<Marketing.GestaoVerbas.ViewModel.FuncionarioViewModel>

@{
    AjaxOptions ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "appendFindFuncionario",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "DefaultAjaxBegin",
        OnComplete = "DefaultAjaxComplete",
        OnSuccess = "findFuncionarioResult",
        OnFailure = "DefaultAjaxFailure",
        HttpMethod = "POST"
    };
}



@using (Ajax.BeginForm("Pesquisar", "Funcionario", ajaxOptions, new { @id = "frmPesquisaFuncionario", @class = "form-pagination" }))
{
    @Html.AntiForgeryToken()

    <div class="modal" tabindex="-1" role="dialog" id="mdlPesquisaFuncionario">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary" style="color:white;">
                    <h5 class="modal-title" id="myModalLabel">Selecionar Funcionario</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body bg-light">
                    <div class="card bg-primary divFiltrosPesquisa">
                        <div class="card-header text-white">
                            <h5>Pesquisar</h5>
                        </div>
                        <div class="card-body bg-light">
                            <div class="row ">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Filtro.CodFuncionario)
                                    @Html.EditorFor(model => model.Filtro.CodFuncionario, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Filtro.NomFuncionario)
                                    @Html.EditorFor(model => model.Filtro.NomFuncionario, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                                </div>
                                <div class="col-md-2 text-right">
                                    <label>&nbsp;</label>
                                    <br />
                                    <button type="submit" id="btnPesquisarFuncionario" class="btn btn-sm btn-primary" title="Pesquisar" value="Pesquisar" >Pesquisar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="card">
                        <div class="card-body bg-secondary grid-paginavel">
                            <div class="row">
                                <div class="table-responsive">
                                    <div class="dataTables_wrapper">
                                        <table class="table table-striped table-bordered table-hover dataTable">
                                            <thead class="bg-secondary">
                                                <tr>
                                                    <th>Ações</th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="CodFuncionario">
                                                            @Html.DisplayNameFor(model => model.Filtro.CodFuncionario)
                                                        </button>
                                                    </th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="NomFuncionario">
                                                            @Html.DisplayNameFor(model => model.Filtro.NomFuncionario)
                                                        </button>
                                                    </th>
                                                    @*<th>
                                                            <button type="submit" class="bg-secondary" style="border:none;" sort-expression="CodEmpresa">
                                                                @Html.DisplayNameFor(model => model.Filtro.CodEmpresa)
                                                            </button>
                                                        </th>
                                                        <th>
                                                            <button type="submit" class="bg-secondary" style="border:none;" sort-expression="NomEmpresa">
                                                                @Html.DisplayNameFor(model => model.Filtro.NomEmpresa)
                                                            </button>
                                                        </th>*@
                                                </tr>
                                            </thead>
                                            <tbody class="bg-light border">
                                                @foreach (var item in Model.Result)
                                                {
                                                    <tr>
                                                        <td>
                                                            <div class="btn-group">
                                                                <button type="button" class="btn btn-sm btn-primary fa fa-check" onclick="findFuncionarioSelect(@item.CodFuncionario.ToString().Replace(",", "."), '@item.NomFuncionario')"></button>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.CodFuncionario)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.NomFuncionario)
                                                        </td>
                                                        @*<td>
                                                                @Html.DisplayFor(modelItem => item.CodEmpresa)
                                                            </td>*@
                                                        @*<td>
                                                                @Html.DisplayFor(modelItem => item.NomEmpresa)
                                                            </td>*@
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                @Html.Partial(Marketing.GestaoVerbas.Core.Grid.Constantes.VIEW_PAGINACAO, Model.Setings, new ViewDataDictionary { TemplateInfo = new TemplateInfo { HtmlFieldPrefix = "Setings" } })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-sm btn-warning">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}