Marketing.GestaoVerbas/Controllers/FornecedorController.cs
using Marketing.GestaoVerbas.Api;
using Marketing.GestaoVerbas.Core;
using Marketing.GestaoVerbas.Core.Grid;
using Marketing.GestaoVerbas.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketing.GestaoVerbas.Controllers
{
    public class FornecedorController : Controller
    {

        [HttpPost]
        public ActionResult Pesquisar(GridSetings<ViewModel.FornecedorViewModel> gridSetings)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (gridSetings.Filtro == null)
            {
                gridSetings.Filtro = new ViewModel.FornecedorViewModel();
                gridSetings.Result = new List<ViewModel.FornecedorViewModel>();
            }
            else if (gridSetings.Filtro.CodFornecedor != null || !string.IsNullOrEmpty(gridSetings.Filtro.NomFornecedor))
            {
                RetornoApi retornoApi = FornecedorApi.List(gridSetings);
                if (retornoApi.Sucesso)
                {
                    gridSetings = (GridSetings<FornecedorViewModel>)retornoApi.Resultado;
                }
                else
                {
                    gridSetings.Result = new List<FornecedorViewModel>();
                    Util.PreencheTempDataAlerta(this, retornoApi);
                }
                if (gridSetings.Result.Count == 0)
                    Util.PreencheTempDataAlerta(this, Core.Message.Constantes.NENHUM_REGISTRO_ENCONTRADO, "Atenção", "info");
            }
            else
            {
                Util.PreencheTempDataAlerta(this, Core.Message.Constantes.INFORME_FILTRO, "Atenção", "info");

                gridSetings.Filtro = new ViewModel.FornecedorViewModel();
                gridSetings.Result = new List<ViewModel.FornecedorViewModel>();
            }         

            return PartialView("~/Views/Fornecedor/findFornecedor.cshtml", gridSetings);
        }

        [HttpGet]
        public string Select(int codigo)
        {
            if (!Util.ValidaSessao())
            {
                return "";
            }

            GridSetings<ViewModel.FornecedorViewModel> gridSetings = new GridSetings<FornecedorViewModel>();
            gridSetings.Filtro = new FornecedorViewModel();

            gridSetings.Filtro.CodFornecedor = codigo;
            gridSetings.Setings = new Setings();

            gridSetings.Setings.Column = "NomFornecedor";
            gridSetings.Setings.Way = "asc";
            gridSetings.Setings.PageSize =  10;
            gridSetings.Setings.CurrentPage = 1;
            

            RetornoApi retornoApi = FornecedorApi.List(gridSetings);
            if (retornoApi.Sucesso)
            {
                gridSetings = (GridSetings<FornecedorViewModel>)retornoApi.Resultado;
            }
            else
            {
                gridSetings.Result = new List<FornecedorViewModel>();
                Util.PreencheTempDataAlerta(this, retornoApi);
            }


            if (gridSetings.Result.Count == 0)
                return "Fornecedor não encontrado!";
            else
                return gridSetings.Result.First().NomFornecedor;
        }
    }
}

Marketing.GestaoVerbas/Views/Fornecedor/findFornecedor.cshtml
@model Marketing.GestaoVerbas.Core.Grid.GridSetings<Marketing.GestaoVerbas.ViewModel.FornecedorViewModel>

@{
    AjaxOptions ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "appendFindFornecedor",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "DefaultAjaxBegin",
        OnComplete = "DefaultAjaxComplete",
        OnSuccess = "findFornecedorResult",
        OnFailure = "DefaultAjaxFailure",
        HttpMethod = "POST"
    };
}



@using (Ajax.BeginForm("Pesquisar", "Fornecedor", ajaxOptions, new { @id = "frmPesquisaFornecedor", @class = "form-pagination" }))
{
    @Html.AntiForgeryToken()

    <div class="modal" tabindex="-1" role="dialog" id="mdlPesquisaFornecedor">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary" style="color:white;">
                    <h5 class="modal-title" id="myModalLabel">Selecionar Fornecedor</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body bg-light">
                    <div class="card bg-primary divFiltrosPesquisa">
                        <div class="card-header text-white">
                            <h5>Pesquisar</h5>
                        </div>
                        <div class="card-body bg-light">
                            <div class="row ">
                                <div class="col-md-4">
                                    @Html.LabelFor(model => model.Filtro.CodFornecedor)
                                    @Html.EditorFor(model => model.Filtro.CodFornecedor, new { htmlAttributes = new { @class = "form-control", id = "txtEditFindFornecedorCodFornecedor", data_val = false, onchange = "findFornecedorCodFornecedorChange('txtEditFindFornecedorCodFornecedor', 'txtEditFindFornecedorNomFornecedor' )" } })

                                </div>
                                <div class="col-md-6">
                                    @Html.LabelFor(model => model.Filtro.NomFornecedor)
                                    @Html.EditorFor(model => model.Filtro.NomFornecedor, new { htmlAttributes = new { @class = "form-control", data_val = false, id = "txtEditFindFornecedorNomFornecedor" } })
                                </div>
                                <div class="col-md-2">
                                    <label>&nbsp;</label>
                                    <br />
                                    <button type="submit" id="btnPesquisarFornecedor" class="btn btn-sm btn-primary" title="Pesquisar" value="Pesquisar" >Pesquisar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="card bg-primary">
                        <div class="card-body bg-secondary grid-paginavel">
                            <div class="row">
                                <div class="table-responsive">
                                    <div class="dataTables_wrapper">
                                        <table class="table table-striped table-bordered table-hover dataTable">
                                            <thead class="bg-secondary">
                                                <tr>
                                                    <th>Ações</th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="CodFornecedor">
                                                            @Html.DisplayNameFor(model => model.Filtro.CodFornecedor)
                                                        </button>
                                                    </th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="NomFornecedor">
                                                            @Html.DisplayNameFor(model => model.Filtro.NomFornecedor)
                                                        </button>
                                                    </th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="CodEmpresa">
                                                            @Html.DisplayNameFor(model => model.Filtro.CodEmpresa)
                                                        </button>
                                                    </th>
                                                    <th>
                                                        <button type="submit" class="" style="border:none;" sort-expression="NomEmpresa">
                                                            @Html.DisplayNameFor(model => model.Filtro.NomEmpresa)
                                                        </button>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody class="bg-light border">
                                                @foreach (var item in Model.Result)
                                                {
                                                    <tr>
                                                        <td>
                                                            <div class="btn-group">
                                                                <button type="button" class="btn btn-sm btn-primary fa fa-check" onclick="findFornecedorSelect(@item.CodFornecedor, '@item.NomFornecedor')"></button>
                                                            </div>
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.CodFornecedor)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.NomFornecedor)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.CodEmpresa)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.NomEmpresa)
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                @Html.Partial(Marketing.GestaoVerbas.Core.Grid.Constantes.VIEW_PAGINACAO, Model.Setings, new ViewDataDictionary { TemplateInfo = new TemplateInfo { HtmlFieldPrefix = "Setings" } })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-sm btn-warning">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}