Marketing.GestaoVerbas/Controllers/NegociacaoController.cs
using Marketing.GestaoVerbas.Api;
using Marketing.GestaoVerbas.Core.Grid;
using Marketing.GestaoVerbas.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Marketing.GestaoVerbas.Controllers
{
    public class NegociacaoController : Controller
    {
        // GET: Negociacao
        [HttpGet]
        public ActionResult Index()
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("5"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            GridSetings<ViewModel.NegociacaoVerbaViewModel> gridSetings = new GridSetings<NegociacaoVerbaViewModel>();
            gridSetings.Filtro = new NegociacaoVerbaViewModel();
            //Atriuir os valores padrão de filtro.

            gridSetings.Result = new List<NegociacaoVerbaViewModel>();

            gridSetings.Setings = new Setings();
            gridSetings.Setings.Column = "DtCadastroNegociacao"; //define ordem Padrão de ordenação
            gridSetings.Setings.Way = "desc";
            gridSetings.Setings.CurrentPage = 1;
            gridSetings.Setings.PageSize = 10;
            gridSetings.Setings.TotalRows = 0;
            gridSetings.Setings.CurrentPageSize = 0;

            RetornoApi retornoApiIndex = CompradorApi.List(new CompradorViewModel());
            if (retornoApiIndex.Sucesso)
            {
                List<CompradorViewModel> compradores = retornoApiIndex.Resultado as List<CompradorViewModel>;
                ViewBag.Compradores = compradores.OrderBy(p => p.NomComprador);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApiIndex);
                ViewBag.Compradores = new List<CompradorViewModel>();
            }

            RetornoApi retornoApiFilial = FilialEmpresaApi.ListLookup();
            if (retornoApiFilial.Sucesso)
            {
                List<FilialEmpresaViewModel> filiais = retornoApiFilial.Resultado as List<FilialEmpresaViewModel>;
                ViewBag.Filiais = filiais;
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApiFilial);
                ViewBag.Filiais = new List<FilialEmpresaViewModel>();
            }

            RetornoApi retornoApi2 = CelulaApi.ListLookup();
            if (retornoApi2.Sucesso)
            {
                List<CelulaViewModel> celulas = retornoApi2.Resultado as List<CelulaViewModel>;
                ViewBag.Celulas = celulas.OrderBy(p => p.NomCelula);
            }


            return View(gridSetings);
        }

        [HttpPost]
        public ActionResult Pesquisar(GridSetings<ViewModel.NegociacaoVerbaViewModel> gridSetings)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("5"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            RetornoApi retornoApiIndex = CompradorApi.List(new CompradorViewModel());
            if (retornoApiIndex.Sucesso)
            {
                List<CompradorViewModel> compradores = retornoApiIndex.Resultado as List<CompradorViewModel>;
                ViewBag.Compradores = compradores.OrderBy(p => p.NomComprador);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApiIndex);
                ViewBag.Compradores = new List<CompradorViewModel>();
            }


            if (gridSetings.Filtro == null)
            {
                gridSetings.Filtro = new ViewModel.NegociacaoVerbaViewModel();
                gridSetings.Result = new List<ViewModel.NegociacaoVerbaViewModel>();
            }
            else
            {
                RetornoApi retornoApiPs = NegociacaoVerbaApi.List(gridSetings);
                if (retornoApiPs.Sucesso)
                {
                    gridSetings = (GridSetings<NegociacaoVerbaViewModel>)retornoApiPs.Resultado;
                }
                else
                {
                    gridSetings.Result = new List<NegociacaoVerbaViewModel>();
                    Util.PreencheTempDataAlerta(this, retornoApiPs);
                }
            }

            if (gridSetings.Result.Count == 0)
                Util.PreencheTempDataAlerta(this, Core.Message.Constantes.NENHUM_REGISTRO_ENCONTRADO, "Atenção", "info");

            RetornoApi retornoApi3 = CelulaApi.ListLookup();
            if (retornoApi3.Sucesso)
            {
                List<CelulaViewModel> celulas = retornoApi3.Resultado as List<CelulaViewModel>;
                ViewBag.Celulas = celulas.OrderBy(p => p.NomCelula);
            }

            RetornoApi retornoApiFilial = FilialEmpresaApi.ListLookup();
            if (retornoApiFilial.Sucesso)
            {
                List<FilialEmpresaViewModel> filiais = retornoApiFilial.Resultado as List<FilialEmpresaViewModel>;
                ViewBag.Filiais = filiais;
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApiFilial);
                ViewBag.Filiais = new List<FilialEmpresaViewModel>();
            }

            return PartialView("~/Views/Negociacao/index.cshtml", gridSetings);
        }

        [HttpPost]
        public ActionResult NovaNegociacao()
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("10"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            NegociacaoVerbaViewModel negociacaoVerbaViewModel = new NegociacaoVerbaViewModel();
            negociacaoVerbaViewModel.CodStatusNegociacaoVenda = 1;


            //Usuario usuario = Session["USUARIO"] as Usuario;
            Usuario usuario = CookieManager.GetCookieObj(CookieEnum.USUARIO);
            negociacaoVerbaViewModel.CodAutor = usuario.Matricula;
            negociacaoVerbaViewModel.NomAutor = usuario.Nome;
            negociacaoVerbaViewModel.VlrVerba = 0;

            RetornoApi retornoApiFilial = FilialEmpresaApi.ListLookup();
            if (retornoApiFilial.Sucesso)
            {
                List<FilialEmpresaViewModel> filiais = retornoApiFilial.Resultado as List<FilialEmpresaViewModel>;
                ViewBag.Filiais = filiais;
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApiFilial);
                ViewBag.Filiais = new List<FilialEmpresaViewModel>();
            }


            ViewBag.Compradores = new List<CompradorViewModel>();
            ViewBag.Fornecedores = new List<FornecedorViewModel>();

            negociacaoVerbaViewModel.Destinos = new List<NegociacaoVerbaDestinoViewModel>();

            return PartialView("~/Views/Negociacao/edit.cshtml", negociacaoVerbaViewModel);
        }

        [HttpPost]
        public ActionResult AddObjetivoDestino(List<NegociacaoVerbaDestinoViewModel> list, NegociacaoVerbaDestinoViewModel obj)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("5"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            if (list == null)
                list = new List<NegociacaoVerbaDestinoViewModel>();

            if (obj.CodDestino != 0 && obj.CodObjetivo != 0 && obj != null)
            {
                if (!(list.Where(x => x.CodObjetivo == obj.CodObjetivo && x.CodDestino == obj.CodDestino).ToList().Count > 0))
                {
                    list.Add(obj);
                }
                else
                {
                    Util.PreencheTempDataAlerta(this, "Esta combinação de Destino\\Objetivo já existe!");
                }
            }
            NegociacaoVerbaViewModel item = new NegociacaoVerbaViewModel();
            item.Destinos = list;
            return PartialView("~/Views/Negociacao/destinoObjetivo.cshtml", list);
        }

        [HttpPost]
        public ActionResult RemoverObjetivoDestino(List<NegociacaoVerbaDestinoViewModel> list, int codigo)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("5"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            list.Remove(list.Where(p => p.CodDestinoObjetivo == codigo).FirstOrDefault());

            return PartialView("~/Views/Negociacao/destinoObjetivo.cshtml", list);
        }

        [HttpPost]
        public ActionResult SalvarNegociacao(NegociacaoVerbaViewModel obj)
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            if (!Util.VerificaMenuUsuario("5"))
            {
                return RedirectToAction("HTTP403", "Error");
            }

            if (obj.Destinos == null)
                obj.Destinos = new List<NegociacaoVerbaDestinoViewModel>();

          
                if (obj.CodNegociacaoVerba == null)
                {
                    Usuario usuario = CookieManager.GetCookieObj(CookieEnum.USUARIO) as Usuario;
                    obj.CodAutor = usuario.Matricula;
                    obj.NomAutor = usuario.Nome;

                    RetornoApi retornoApi = NegociacaoVerbaApi.Insert(obj);
                    if (retornoApi.Sucesso)
                    {
                        obj = retornoApi.Resultado as NegociacaoVerbaViewModel;

                        return EditarNegociacao(obj.CodNegociacaoVerba.Value);
                    }
                    else

Marketing.GestaoVerbas/Views/Negociacao/acordosNegociacao.cshtml
@using Marketing.GestaoVerbas.ViewModel
@model IEnumerable<AcordoViewModel>


@{
    foreach (var item in Model)
    {
    }
}



<div class="modal" id="modalAcordosNegociacao" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary" style="color:white;">
                <h5 class="modal-title" id="myModalLabel">Aprovar Negociação</h5>
            </div>
            <div class="modal-body bg-light">
                @{
                    NegociacaoVerbaViewModel negociacao = ViewBag.NegociacaoVerba;
                }

                <div class="row">
                    <div class="col-md-6">
                        @Html.LabelFor(model => negociacao.CodNegociacaoVerba)
                        @Html.EditorFor(model => negociacao.CodNegociacaoVerba, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(model => negociacao.NomStatusNegociacaoVenda)
                        @Html.EditorFor(model => negociacao.NomStatusNegociacaoVenda, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                </div>


                <h4>Acordos</h4>
                <br />

                @foreach (AcordoViewModel acordo in Model)
                {
                    <div class="row">
                        <div class="col-md-4">
                            @Html.LabelFor(model => acordo.Recebimentos.First().NomDestinoObjetivo)
                            @Html.EditorFor(model => acordo.Recebimentos.First().NomDestinoObjetivo, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </div>
                        <div class="col-md-4">
                            @Html.LabelFor(model => acordo.Recebimentos.First().VlrNegociado)
                            @Html.EditorFor(model => acordo.Recebimentos.First().VlrNegociado, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </div>
                        <div class="col-md-4">
                            @Html.LabelFor(model => acordo.CodPromessa)
                            @Html.EditorFor(model => acordo.CodPromessa, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                        </div>
                    </div>
                }

            </div>
            <div class="modal-footer">
                <button type="button" title="Fechar" class="btn btn-default" style="cursor: pointer;background-color:orange" onclick="jsCloseModalAcordosNegociacao()">Fechar</button>
            </div>
        </div>
    </div>
</div>

Marketing.GestaoVerbas/Views/Negociacao/aprovarAcordo.cshtml
@using Marketing.GestaoVerbas.ViewModel
@model IEnumerable<AcordoViewModel>

Marketing.GestaoVerbas/Views/Negociacao/findNegociacao.cshtml
@model Marketing.GestaoVerbas.Core.Grid.GridSetings<Marketing.GestaoVerbas.ViewModel.NegociacaoVerbaViewModel>

@{
    AjaxOptions ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "appendFindNegociacao",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "DefaultAjaxBegin",
        OnComplete = "DefaultAjaxComplete",
        OnSuccess = "findNegociacaoResult",
        OnFailure = "DefaultAjaxFailure",
        HttpMethod = "POST"
    };
}



@using (Ajax.BeginForm("FindNegociacao", "Negociacao", ajaxOptions, new { @id = "frmPesquisaNegociacao", @class = "form-pagination" }))
{
    @Html.AntiForgeryToken()

    <div class="modal" tabindex="-1" role="dialog" id="mdlPesquisaNegociacao">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary" style="color:white;">
                    <h5 class="modal-title" id="myModalLabel">Selecionar Negociação</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body bg-light">
                    <div class="container card bg-primary divFiltrosPesquisa">
                        <div class="py-1" style="color:white;">
                            <h5>Pesquisar</h5>
                        </div>
                        <div class="row bg-light">
                            <div class="col-4">
                                @Html.LabelFor(model => model.Filtro.CodNegociacaoVerba)
                                @Html.EditorFor(model => model.Filtro.CodNegociacaoVerba, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                            </div>
                            <div class="col-6">
                                @Html.LabelFor(model => model.Filtro.DesNegociacaoVerba)
                                @Html.EditorFor(model => model.Filtro.DesNegociacaoVerba, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                            </div>
                            <div class="col-2">
                                <label>&nbsp;</label>
                                <br />
                                <input type="submit" id="btnPesquisarNegociacao" class="btn btn-sm btn-primary" title="Pesquisar" value="Pesquisar" />
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="container card bg-primary">
                        <div class="row bg-secondary">
                            <div class="table-responsive">
                                <div class="dataTables_wrapper">
                                    <table class="table table-striped table-bordered table-hover dataTable">
                                        <thead class="bg-secondary">
                                            <tr>
                                                <th>Ações</th>
                                                <th>
                                                    <button type="submit" class="bg-secondary" style="border:none;" sort-expression="NomNegociacao">
                                                        @Html.DisplayNameFor(model => model.Filtro.CodNegociacaoVerba)
                                                    </button>
                                                </th>
                                                <th>
                                                    <button type="submit" class="bg-secondary" style="border:none;" sort-expression="NomNegociacao">
                                                        @Html.DisplayNameFor(model => model.Filtro.DesNegociacaoVerba)
                                                    </button>
                                                </th>

                                            </tr>
                                        </thead>
                                        <tbody class="bg-light border">
                                            @foreach (var item in Model.Result)
                                            {
                                                <tr>
                                                    <td>
                                                        <div class="btn-group">
                                                            <button type="button" class="btn btn-sm btn-primary fa fa-check" onclick="findNegociacaoSelect(@item.CodNegociacaoVerba, '@item.DesNegociacaoVerba')"></button>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.CodNegociacaoVerba)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.DesNegociacaoVerba)
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            @Html.Partial(Marketing.GestaoVerbas.Core.Grid.Constantes.VIEW_PAGINACAO, Model.Setings, new ViewDataDictionary { TemplateInfo = new TemplateInfo { HtmlFieldPrefix = "Setings" } })


                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-sm btn-warning">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

Marketing.GestaoVerbas/Views/Negociacao/imprimirAcordo.cshtml
@using Marketing.GestaoVerbas.ViewModel
@model IEnumerable<AcordoViewModel>


@{
    foreach (var item in Model)
    {
    }
}



<div class="modal" id="modalImprimirAcordos" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary" style="color:white;">
                <h5 class="modal-title" id="myModalLabel">Imprimir Acordos</h5>
            </div>
            <div class="modal-body bg-light">
                @{
                NegociacaoVerbaViewModel negociacao = ViewBag.NegociacaoVerba;
                }

                <div class="card bg-primary">
                    <div class="card-header text-white">
                        <h5>Acordos</h5>
                    </div>
                    <div class="card-body bg-secondary">
                        <div class="row">
                            <div class="table-responsive">
                                <div class="dataTables_wrapper">
                                    <table id="tbGrid" class="table table-hover table-striped  table-bordered">
                                        <thead class="bg-secondary">
                                            <tr>
                                                <th class="center border">
                                                </th>
                                                <th>Negociação</th>
                                                <th>Acordo</th>
                                                <th>Empenho</th>
                                                <th>Valor</th>
                                            </tr>
                                        </thead>
                                        <tbody class="bg-light">
                                            @foreach (AcordoViewModel acordo in Model)
                                        {
                                            <tr>
                                                <td>
                                                    <a class="btn fa fa-print" target="_blank" href="@Url.Action("ImprimirAcordo", "Negociacao",  new { pCodPromessa = acordo.CodPromessa })" title="Imprimir">
                                                    </a>
                                                </td>
                                                <td>@Html.DisplayFor(model => negociacao.CodNegociacaoVerba)</td>
                                                <td>@Html.DisplayFor(model => acordo.CodPromessa)</td>
                                                <td>@Html.DisplayFor(model => acordo.Recebimentos.First().NomDestinoObjetivo)</td>
                                                <td>@Html.DisplayFor(model => acordo.Recebimentos.First().VlrNegociado)</td>
                                            </tr>
                                    }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" title="Fechar" class="btn btn-default" style="cursor: pointer;background-color:orange" onclick="jsCloseModalImprimirAcordos()">Fechar</button>
            </div>
        </div>
    </div>
</div>

Marketing.GestaoVerbas/Views/Negociacao/justificativaReprovacao.cshtml
@using Marketing.GestaoVerbas.ViewModel
@model NegociacaoVerbaViewModel

    <div class="modal" id="modalJustificaReprovacao" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header bg-primary" style="color:white;">
                    <h5 class="modal-title" id="myModalLabel">Justificativa</h5>
                </div>
                <div class="modal-body bg-light">
                    <div class="row">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.DesJustificativaReprovacao)
                            @Html.TextAreaFor(model => model.DesJustificativaReprovacao, new { @class = "form-control", id = "txtDesJustificativaReprovacao", rows = "4" } )
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" title="Salvar" class="btn btn-default" style="cursor: pointer;" onclick="jsGACReprovarNegociacao(@Model.CodNegociacaoVerba)">Salvar</button>
                        <button type="button" title="Fechar" class="btn btn-default" style="cursor: pointer;background-color:orange" onclick="jsCloseModalJustificativaReprovacao()">Fechar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

Marketing.GestaoVerbas/Views/Negociacao/pendencias.cshtml
@using Marketing.GestaoVerbas.Core.Grid
@using Marketing.GestaoVerbas.ViewModel

@model  GridSetings<NegociacaoVerbaViewModel>

@{
    ViewBag.Title = "Negociação";
}

<div class="container-fluid">

    @using (Ajax.BeginForm("PesquisarPendencias", "Negociacao", Marketing.GestaoVerbas.Core.Ajax.Constantes.AJAX_PESQUISA_POST_DEFAULT(), new { @id = "formPesquisaPendencias", @class = "form-pagination" }))
    {
        <br />
        <div class="card bg-primary divFiltrosPesquisa">
            <div class="card-header text-white" >
                <h3>Filtros</h3>
            </div>
            <div class="card-body bg-light">
                <div class="row">

                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Filtro.NomFornecedor)
                        <div class="row">
                            <div class="col-4">
                                @Html.EditorFor(model => model.Filtro.CodFornecedor, new { htmlAttributes = new { @class = "form-control", id = "txtFiltroPendenciaVerbaCodFornecedor", data_val = false, onchange = "findFornecedorCodFornecedorChange('txtFiltroPendenciaVerbaCodFornecedor', 'txtFiltroPendenciaVerbaNomFornecedor' )" } })
                            </div>
                            <div class="col-8">
                                <div class="input-group">
                                    @Html.EditorFor(model => model.Filtro.NomFornecedor, new { htmlAttributes = new { @class = "form-control", data_val = false, id = "txtFiltroPendenciaVerbaNomFornecedor" } })

                                    <button type="button" class="input-group-addon" title="Pesquisar Filial" style="cursor: pointer;background-color: #196dab;color:white;padding-top:10px;padding-bottom: 10px;" id="btnOpenModal" onclick="jsOpenModalFornecedorPendencia()"><i class="fa fa-search center"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Filtro.NomAutor)
                        <div class="row">
                            <div class="col-4">
                                @Html.EditorFor(model => model.Filtro.CodAutor, new { htmlAttributes = new { @class = "form-control", data_val = false, id = "txtFiltroPendenciaVerbaCodAutor", onchange = "findFuncionarioCodFuncionarioChange('txtFiltroPendenciaVerbaCodAutor', 'txtFiltroPendenciaVerbaNomAutor' )" } })
                            </div>
                            <div class="col-8">
                                <div class="input-group">
                                    @Html.EditorFor(model => model.Filtro.NomAutor, new { htmlAttributes = new { @class = "form-control", data_val = false, id = "txtFiltroPendenciaVerbaNomAutor" } })
                                    <button type="button" class="input-group-addon" title="Pesquisar Filial" style="cursor: pointer;background-color: #196dab;color:white;padding-top:10px;padding-bottom: 10px;" id="btnOpenModal" onclick="jsOpenModalAutorPendencia()"><i class="fa fa-search center"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-2">
                        @Html.LabelFor(model => model.Filtro.CodNegociacaoVerba)
                        @Html.EditorFor(model => model.Filtro.CodNegociacaoVerba, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                    </div>
                    <div class="col-md-6">
                        @Html.LabelFor(model => model.Filtro.DesNegociacaoVerba)
                        @Html.EditorFor(model => model.Filtro.DesNegociacaoVerba, new { htmlAttributes = new { @class = "form-control", data_val = false } })
                    </div>
                    <div class="col-md-4">
                        <br />
                        <div class="pull-right">
                            <button type="submit" title="Pesquisar" class="btn" style="cursor: pointer;background-color: #196dab;" id="" value="" required=""><i class="fa fa-search"></i> Pesquisar</button>
                            <button type="button" class="btn" style="cursor: pointer;background-color: #196dab;" title="Limpar campos de filtro" onclick="jsLimparFiltrosPesquisa()"><i class="fa fa-eraser"></i> Limpar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br />

        <div class="grid-paginavel">
            @foreach (var item in Model.Result)
            {
                <div class="card bg-primary" onclick="jsEditarPendencia(@item.CodNegociacaoVerba)">

                    <div class="card-header text-white" >
                        <h5> @Html.DisplayFor(modelItem => item.CodNegociacaoVerba)  -  @Html.DisplayFor(modelItem => item.DesNegociacaoVerba)</h5>
                    </div>
                    <div class="card-body bg-light">
                        <ul style="cursor: pointer;">
                            <li style="list-style-type: none;">
                                <i class="fa fa-fw fa-industry"></i>&nbsp;Fornecedor: @Html.DisplayFor(modelItem => item.CodFornecedor) -  @Html.DisplayFor(modelItem => item.NomFornecedor)
                                <br />
                                <i class="fa fa-fw fa-user-circle"></i>&nbsp;Comprador: @Html.DisplayFor(modelItem => item.CodComprador) - @Html.DisplayFor(modelItem => item.NomComprador)
                                <br />
                                <i class="fa fa-fw fa-user"></i>&nbsp;Autor: @Html.DisplayFor(modelItem => item.CodAutor) - @Html.DisplayFor(modelItem => item.NomAutor)
                                <br />
                                <i class="fa fa-fw fa-money"></i>&nbsp;Valor: @Html.DisplayFor(modelItem => item.VlrVerba)
                                <br />
                                <i class="fa fa-fw fa-calendar"></i>&nbsp;Data: @Html.DisplayFor(modelItem => item.DtCadastroNegociacao)
                            </li>
                        </ul>
                    </div>
                </div>

                <br />
            }
            <div class="card ">
                <div class="card-body bg-secondary">
                    <div class="row">
                        @Html.Partial(Constantes.VIEW_PAGINACAO, Model.Setings, new ViewDataDictionary { TemplateInfo = new TemplateInfo { HtmlFieldPrefix = "Setings" } })
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="aprovaNegociacao" id="aprovaNegociacao"></div>
    <div id="formEdit"></div>
    <div id="appendFind"></div>
</div>

<!-- Script -->
@section Scripts {
    @Scripts.Render("~/Scripts/pagina/negociacao-verba.js")
    @Scripts.Render("~/Scripts/pagina/carimbo.js")
    @Scripts.Render("~/Scripts/find/funcionario.js")
    @Scripts.Render("~/Scripts/find/filialEmpresa.js")
    @Scripts.Render("~/Scripts/find/fornecedor.js")
}