Marketing.GestaoVerbas/Controllers/RelatoriosVerbasEmitidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Marketing.GestaoVerbas.ViewModel;
using Marketing.GestaoVerbas.Core.Grid;
using Marketing.GestaoVerbas.Api;
using System.Text.RegularExpressions;
using System.IO;
using System.Web.Hosting;
using System.Text;
using System.Net;

namespace Marketing.GestaoVerbas.Controllers
{
    public class RelatoriosVerbasEmitidasController : Controller
    {
        // GET: Relatorios
        public ActionResult Index()
        {
            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            GridSetings<ViewModel.RelatoriosVerbasEmitidasViewModel> gridSetings = new GridSetings<RelatoriosVerbasEmitidasViewModel>();
            gridSetings.Filtro = new RelatoriosVerbasEmitidasViewModel();

            //Atriuir os valores padrão de filtro.
            gridSetings.Filtro.DtCadastroCarimboInicio = DateTime.Now.AddDays(-7);
            gridSetings.Filtro.DtCadastroCarimboFim = DateTime.Now;
            gridSetings.Filtro.DtCadastroNegociacaoInicio = DateTime.Now.AddDays(-7);
            gridSetings.Filtro.DtCadastroNegociacaoFim = DateTime.Now;
            gridSetings.Filtro.CodStatusNegociacao = 3;

            gridSetings.Result = new List<RelatoriosVerbasEmitidasViewModel>();

            gridSetings.Setings = new Setings();
            gridSetings.Setings.Column = "DtCadastroCarimbo"; //define ordem Padrão de ordenação
            gridSetings.Setings.Way = "desc";
            gridSetings.Setings.CurrentPage = 1;
            gridSetings.Setings.PageSize = 10;
            gridSetings.Setings.TotalRows = 0;
            gridSetings.Setings.CurrentPageSize = 0;

            RetornoApi retornoApi = CompradorApi.List(new CompradorViewModel());
            if (retornoApi.Sucesso)
            {
                List<CompradorViewModel> compradores = retornoApi.Resultado as List<CompradorViewModel>;
                ViewBag.Compradores = compradores.OrderBy(p => p.NomComprador);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Compradores = new List<CompradorViewModel>();
            }

            RetornoApi retornoApi2 = CelulaApi.ListLookup();
            if (retornoApi2.Sucesso)
            {
                List<CelulaViewModel> celulas = retornoApi2.Resultado as List<CelulaViewModel>;
                ViewBag.Celulas = celulas.OrderBy(p => p.NomCelula);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Celulas = new List<CelulaViewModel>();
            }

            RetornoApi retornoApi3 = FilialEmpresaApi.ListLookup();
            if (retornoApi3.Sucesso)
            {
                List<FilialEmpresaViewModel> filiais = retornoApi3.Resultado as List<FilialEmpresaViewModel>;
                ViewBag.Filiais = filiais.OrderBy(p => p.CodFilialEmpresa);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Filiais = new List<FilialEmpresaViewModel>();
            }


            return View(gridSetings);
        }

        [HttpPost]
        public ActionResult Pesquisar(GridSetings<RelatoriosVerbasEmitidasViewModel> gridSetings)
        {

            if (!Util.ValidaSessao())
            {
                return RedirectToAction("Index", "Login");
            }

            RetornoApi retornoApi = null;
            if (gridSetings == null)
            {
                gridSetings.Filtro = new ViewModel.RelatoriosVerbasEmitidasViewModel();
                gridSetings.Result = new List<ViewModel.RelatoriosVerbasEmitidasViewModel>();
            }
            else
            {
                switch (gridSetings.Filtro.IndRelVisao)
                {
                    case "N":
                        retornoApi = RelatoriosVerbasEmitidasApi.PorNegociacaoVerba(gridSetings);
                        break;
                    case "E":
                        retornoApi = RelatoriosVerbasEmitidasApi.PorNegociacaoVerbaEmpenho(gridSetings);
                        break;
                    case "M":
                        retornoApi = RelatoriosVerbasEmitidasApi.PorCarrimboMercadoria(gridSetings);
                        break;
                    case "F":
                        retornoApi = RelatoriosVerbasEmitidasApi.PorCarrimboFornecedor(gridSetings);
                        break;
                }

                if (retornoApi.Sucesso)
                {
                    gridSetings = (GridSetings<RelatoriosVerbasEmitidasViewModel>)retornoApi.Resultado;
                }
                else
                {
                    gridSetings.Result = new List<RelatoriosVerbasEmitidasViewModel>();
                    Util.PreencheTempDataAlerta(this, retornoApi);
                }
                if (gridSetings.Result.Count == 0)
                    Util.PreencheTempDataAlerta(this, Core.Message.Constantes.NENHUM_REGISTRO_ENCONTRADO, "Atenção", "info");
            }

      

            retornoApi = CompradorApi.List(new CompradorViewModel());
            if (retornoApi.Sucesso)
            {
                List<CompradorViewModel> compradores = retornoApi.Resultado as List<CompradorViewModel>;
                ViewBag.Compradores = compradores.OrderBy(p => p.NomComprador);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Compradores = new List<CompradorViewModel>();
            }

            RetornoApi retornoApi2 = FilialEmpresaApi.ListLookup();
            if (retornoApi.Sucesso)
            {
                List<FilialEmpresaViewModel> filiais = retornoApi2.Resultado as List<FilialEmpresaViewModel>;
                ViewBag.Filiais = filiais.OrderBy(p => p.CodFilialEmpresa);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Filiais = new List<FilialEmpresaViewModel>();
            }

            RetornoApi retornoApi3 = CelulaApi.ListLookup();
            if (retornoApi3.Sucesso)
            {
                List<CelulaViewModel> celulas = retornoApi3.Resultado as List<CelulaViewModel>;
                ViewBag.Celulas = celulas.OrderBy(p => p.NomCelula);
            }
            else
            {
                Util.PreencheTempDataAlerta(this, retornoApi);
                ViewBag.Celulas = new List<CelulaViewModel>();
            }

            return PartialView("~/Views/RelatoriosVerbasEmitidas/index.cshtml", gridSetings);
        }

        [HttpPost]
        public ActionResult ExportarRelatorioCSV(GridSetings<RelatoriosVerbasEmitidasViewModel> gridSetings)
        {
            //Consulta 
            RetornoApi retornoApi = null;
            switch (gridSetings.Filtro.IndRelVisao)
            {
                case "N":
                    retornoApi = RelatoriosVerbasEmitidasApi.PorNegociacaoVerba(gridSetings);
                    break;
                case "E":
                    retornoApi = RelatoriosVerbasEmitidasApi.PorNegociacaoVerbaEmpenho(gridSetings);
                    break;
                case "M":
                    retornoApi = RelatoriosVerbasEmitidasApi.PorCarrimboMercadoria(gridSetings);
                    break;
                case "F":
                    retornoApi = RelatoriosVerbasEmitidasApi.PorCarrimboFornecedor(gridSetings);
                    break;

            }

            if (retornoApi.Sucesso)
            {
                gridSetings = (GridSetings<RelatoriosVerbasEmitidasViewModel>)retornoApi.Resultado;

                string handle = Guid.NewGuid().ToString();

                if (gridSetings.Filtro.IndRelVisao == "N")
                {
                    TempData[handle] = (new Core.CSV<RelatoriosVerbasEmitidasViewModel>()).ConvertCSV(gridSetings.Result
                                            , new string[] { "CodNegociacaoVerba"
                                                           , "NomNegociacaoVerba"
                                                           , "NomStatusNegociacao"
                                                           , "DtCadastroNegociacao"
                                                           , "CodFornecedor"
                                                           , "NomFornecedor"
                                                           , "CodFilialEmpresa"
                                                           , "NomFilialEmpresa"
                                                           , "VlrVerbaNegociacao"
                                                           , "DesObservacaoSolicitacao"
                                                           }
                                        );


                }
                if (gridSetings.Filtro.IndRelVisao == "E")
                {
                    TempData[handle] = (new Core.CSV<RelatoriosVerbasEmitidasViewModel>()).ConvertCSV(gridSetings.Result
                                           , new string[] { "CodNegociacaoVerba"
                                                          , "NomNegociacaoVerba"
                                                          , "NomStatusNegociacao"
                                                          , "DtCadastroNegociacao"
                                                          , "NomDestino"
                                                          , "NomObjetivo"
                                                          , "NomDestinoObjetivo"
                                                          , "CodFornecedor"
                                                          , "NomFornecedor"
                                                          , "CodCarimbo"

Marketing.GestaoVerbas/Views/RelatoriosVerbasEmitidas/relPorFornecedor.cshtml
@using Marketing.GestaoVerbas.Core.Grid
@using Marketing.GestaoVerbas.ViewModel
@model  RelatoriosVerbasEmitidasViewModel



<div class="fixed-nav-content">
    
        <div class="container">
            <div class="row py-1">
                <div class="mx-auto">
                    <ul class="nav nav-pills" style="font-size:25px;">
                        <li class="nav-item">
                            <button type="button" onclick="ModeIndex()" title="Voltar" class="nav-link" style="background-color:transparent;border:none;"> <i class="fa fa-arrow-left"></i>&nbsp;@Html.ActionLink(" ", "Index", "RelatoriosVerbasEmitidas", new { area = "" }, new { onclick = "true;", @class = "" })</button>
                        </li>
                        <li class="nav-item">
                            <button type="button" title="Exportar" class="nav-link" style="background-color:transparent;border:none;"> <i class="fa fa-save"></i>&nbsp;</button>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="dropdown-divider" style="margin-top:-12px;"></div>
            <br />
        </div>

        <div class="container card bg-primary" style="padding-bottom:2px; overflow: auto">

            <div class="py-1" style="color:white;">
                <h5>Relatório por Fornecedor</h5>
            </div>

            <div class="row bg-secondary">
                <table id="tb" class="table" style="margin: 0px;width:100%;table-layout:inherit;overflow: scroll;">
                    <thead class="bg-secondary">
                        <tr role="row">
                            <th class="sorting border">                 </th>
                            <th class="sorting border">Grupo de Similares            </th>
                            <th class="sorting border">Data             </th>
                            <th class="sorting border">Cód. Carimbo     </th>
                            <th class="sorting border">Situação         </th>
                            <th class="sorting border">Destino          </th>
                            <th class="sorting border">Objetivo         </th>
                            <th class="sorting border">Entidade         </th>
                            <th class="sorting border">Cód. Fornecedor  </th>
                            <th class="sorting border">Fornecedor       </th>
                            <th class="sorting border">Valor            </th>
                            <th class="sorting border">Observação       </th>
                        </tr>
                    </thead>

                    <tbody class="bg-light border" id="tbodyRelatorioItem">

                        <tr class="row-similar-group row-similar-group row-style-strong">
                            <td class="border"><i class="fa fa-plus" style="cursor:pointer;" onclick="jsExpandeSimilaresRelatorio(1)"></i></td>
                            <td class="border">Grupo Similar 1            </td>
                            <td class="border">             </td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border">10000,00</td>
                            <td class="border"></td>

                        </tr>
                        <tr class="filho-1 row-similar-item row-style-strong" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Grupo Similar 1            </td>
                            <td class="border">23/02/2018             </td>
                            <td class="border">000     </td>
                            <td class="border">Aguardando Aprovação        </td>
                            <td class="border">Destino          </td>
                            <td class="border">Objetivo         </td>
                            <td class="border">Entidade 04        </td>
                            <td class="border">04  </td>
                            <td class="border">Fornecedor 04       </td>
                            <td class="border">1000,00            </td>
                            <td class="border">Observação 04      </td>
                        </tr>
                        <tr class="row-similar-group row-similar-group row-style-weak">
                            <td class="border"><i class="fa fa-plus" style="cursor:pointer;" onclick="jsExpandeSimilaresRelatorio(2)"></i></td>
                            <td class="border">Grupo Similar 2            </td>
                            <td class="border">             </td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border">10000,00</td>
                            <td class="border"></td>
                        </tr>
                        <tr class="filho-2 row-similar-item row-style-weak" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Grupo Similar 2            </td>
                            <td class="border">23/02/2018             </td>
                            <td class="border">000     </td>
                            <td class="border">Aguardando Aprovação        </td>
                            <td class="border">Destino          </td>
                            <td class="border">Objetivo         </td>
                            <td class="border">Entidade 04        </td>
                            <td class="border">04  </td>
                            <td class="border">Fornecedor 04       </td>
                            <td class="border">1000,00            </td>
                            <td class="border">Observação 04      </td>
                        </tr>
                        <tr class="row-no-similar-group row-style-strong">
                            <td class="border"><i class="fa fa-plus" style="cursor:pointer;" onclick="jsExpandeSimilaresRelatorio(3)"></i></td>
                            <td class="border">Sem Similares            </td>
                            <td class="border">             </td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border">10000,00</td>
                            <td class="border"></td>
                        </tr>
                        <tr class="filho-3 row-no-similar-item row-style-strong" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Sem Similares            </td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border"></td>
                            <td class="border">10000,00</td>
                            <td class="border"></td>
                        </tr>
                        <tr class="filho-3 row-no-similar-item row-style-weak" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Sem Similares            </td>
                            <td class="border">23/02/2018             </td>
                            <td class="border">000     </td>
                            <td class="border">Aguardando Aprovação        </td>
                            <td class="border">Destino          </td>
                            <td class="border">Objetivo         </td>
                            <td class="border">Entidade 04        </td>
                            <td class="border">04  </td>
                            <td class="border">Fornecedor 04       </td>
                            <td class="border">1000,00            </td>
                            <td class="border">Observação 04      </td>
                        </tr>
                        <tr class="filho-3 row-no-similar-item row-style-strong" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Sem Similares            </td>
                            <td class="border">23/02/2018             </td>
                            <td class="border">000     </td>
                            <td class="border">Aguardando Aprovação        </td>
                            <td class="border">Destino          </td>
                            <td class="border">Objetivo         </td>
                            <td class="border">Entidade 04        </td>
                            <td class="border">04  </td>
                            <td class="border">Fornecedor 04       </td>
                            <td class="border">1000,00            </td>
                            <td class="border">Observação 04      </td>
                        </tr>
                        <tr class="filho-3 row-no-similar-item row-style-weak" style="display:none;">
                            <td class="border"></td>
                            <td class="border">Sem Similares            </td>
                            <td class="border">23/02/2018             </td>
                            <td class="border">000     </td>
                            <td class="border">Aguardando Aprovação        </td>
                            <td class="border">Destino          </td>
                            <td class="border">Objetivo         </td>
                            <td class="border">Entidade 04        </td>
                            <td class="border">04  </td>
                            <td class="border">Fornecedor 04       </td>
                            <td class="border">1000,00            </td>
                            <td class="border">Observação 04      </td>
                        </tr>

                    </tbody>
                </table>

            </div>
            <div class="row bg-light">

            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    
</div>
    <style>

        .row-similar-group.row-style-strong {
            background-color: #B0E0E6;
        }

        .row-similar-group.row-style-weak {
            background-color: paleturquoise;
        }


        .row-similar-item.row-style-strong {
            background-color: lightcyan;
        }

        .row-similar-item.row-style-weak {
            background-color: #F0FFFF;
        }

        .row-no-similar-item.row-style-strong {
            background-color: #FFFACD;
        }

        .row-no-similar-item.row-style-weak {
            background-color: #EEE8AA;
        }

        .row-no-similar-group {
            background-color: #F0E68C;
        }

        #tbodyCarimboItem td {
            white-space: nowrap;
        }
    </style>